import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import Card from "../components/Card";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          property="og:image"
          content="https://images.unsplash.com/photo-1659647009813-d45b7a167900?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=765&q=80"
        />
        <meta property="og:title" content="Your Title" />
        <meta
          property="og:description"
          content="A full description of the page."
        />
      </Head>
      <Banner />
      <Card />
    </>
  );
};

export default Home;
